### ISSUE TITLE
部署后页面空白

### ISSUE THREAD

**Issue by zhtsu** [Nomango/OnePage#1]
你好，前辈。
我 fork 了你的项目并且将其分别部署到了 github pages 和 cloudflare ，但是页面都没有正确显示内容，请问应该如何解决？
浏览器报错如下：

Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/jsx". Strict MIME type checking is enforced for module scripts per HTML spec.

<a href="https://s1.ax1x.com/2022/08/11/v8MemV.png"><img src="https://s1.ax1x.com/2022/08/11/v8MemV.png" alt="v8MemV.png" border="0" /></a>

**Comment by Nomango** [comment]
@zhtsu 因为它是个React项目，如果是cloudflare的话需要在构建命令中填写 `npm run build`（好像新建时选择 React 会默认填上），在输出目录填写`/dist`，部署后就可以看到页面了。

如果是Github Pages会麻烦一些，需要你对Github Actions比较熟悉，在Pages设置中选 Github Actions 部署，可以用 Static HTML 为模板，在 deploy.steps 中添加 `npm run build` 命令，然后在 actions/upload-pages-artifact 这一步填写参数为 `path=/dist`

**Comment by zhtsu** [comment]
@Nomango 感谢前辈，使用cloudflare的方案成功了。另外，前辈的 2D 游戏引擎写得太棒了，Easy2D 和 Kiwano 都是，向前辈学习！

**Comment by Nomango** [comment]
@zhtsu 加油
